server:
  port: 8082

spring:
  profiles:
    active: local

  datasource-oracle:
    driver-class-name: oracle.jdbc.OracleDriver
    jdbc-url: jdbc:oracle:thin:@211.252.87.18:1521/ORCL
    username: dtpmgr
    password: dtpmgr123!
    minimumIdle : 3
    maximumPoolSize : 3
    idleTimeout : 30000
    maxLifetime : 2000000
    connectionTimeout : 30000
    jndi-name: java:comp/env/dtpData

  servlet:  
    multipart:
      enabled: false
  main:
    allow-bean-definition-overriding: true
  mvc:
    view:
      prefix: /WEB-INF/jsp      
      suffix: .jsp

  jackson:
    property-naming-strategy: SNAKE_CASE

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    generate-ddl: true
    defer-datasource-initialization: true

# MyBatis 설정
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.backend.domain

# H2 설정 (주석 처리된 부분)
# spring:
#   h2:
#     console:
#       enabled: true
#       settings:
#         web-allow-others: true
#       path: /h2-console
